language: python
python:
  - "3.3"
  - "3.4"
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran
before_install:
  - pip install -U pip
install:
  - pip install .
script:
  - nosetests
